import { AnalysisResultData } from '../../models/AnalysisSession';

/**
 * Generates a structured memo from analysis results.
 * Uses template-based narration (deterministic, no LLM dependency).
 * Can be extended to call AWS Bedrock for more natural narratives.
 */
export function generateMemo(result: Omit<AnalysisResultData, 'memoMarkdown'>): string {
  const lines: string[] = [];

  lines.push('# Root Cause Analysis Report');
  lines.push('');
  lines.push(`**Generated:** ${new Date().toISOString().slice(0, 16).replace('T', ' ')}`);
  lines.push('');

  lines.push('## Executive Summary');
  lines.push('');
  if (result.rootCauses.length > 0) {
    const primary = result.rootCauses[0];
    lines.push(`Primary root cause identified: **${primary.title}** (${primary.confidence * 100}% confidence, ${primary.contribution}% contribution).`);
    lines.push('');
    lines.push(primary.description);
  } else {
    lines.push('No significant root causes detected in the current data.');
  }
  lines.push('');

  lines.push('## Business Impact');
  lines.push('');
  const impact = result.businessImpact;
  lines.push(`- **Estimated Lost Revenue:** ${impact.lostRevenueFormatted}`);
  if (impact.conversionDrop > 0) lines.push(`- **Conversion Drop:** ${impact.conversionDrop.toFixed(1)}%`);
  if (impact.oosSkus > 0) lines.push(`- **Out-of-Stock SKUs:** ${impact.oosSkus}`);
  if (impact.slaBreaches > 0) lines.push(`- **SLA Breaches:** ${impact.slaBreaches}`);
  if (impact.stockAtHQ > 0) lines.push(`- **Stock at HQ:** ${impact.stockAtHQ} units (idle)`);
  lines.push('');

  if (result.rootCauses.length > 0) {
    lines.push('## Root Causes (Ranked)');
    lines.push('');
    for (const rc of result.rootCauses) {
      lines.push(`### ${rc.title}`);
      lines.push(`- **Confidence:** ${(rc.confidence * 100).toFixed(0)}%`);
      lines.push(`- **Contribution:** ${rc.contribution}%`);
      lines.push(`- **Description:** ${rc.description}`);
      if (rc.contributingFactors.length > 0) {
        lines.push(`- **Factors:** ${rc.contributingFactors.join('; ')}`);
      }
      lines.push('');
    }
  }

  if (result.actions.length > 0) {
    lines.push('## Recommended Actions');
    lines.push('');
    lines.push('| Priority | Action | Owner | Expected Impact |');
    lines.push('|----------|--------|-------|-----------------|');
    for (const a of result.actions) {
      lines.push(`| ${a.priority.toUpperCase()} | ${a.title}: ${a.description} | ${a.owner} | ${a.expectedImpact} |`);
    }
    lines.push('');
  }

  if (result.geoOpportunity) {
    lines.push('## Geographic Opportunity');
    lines.push('');
    lines.push(`**${result.geoOpportunity.originLabel}** → **${result.geoOpportunity.destinationLabel}**`);
    lines.push('');
    lines.push(result.geoOpportunity.narrative);
    lines.push('');
  }

  lines.push('---');
  lines.push('*This report was generated by the Agentic Decision Intelligence Platform. All findings are grounded in data evidence.*');

  return lines.join('\n');
}

export function generateChatResponse(
  query: string,
  result: AnalysisResultData
): string {
  const parts: string[] = [];

  if (result.rootCauses.length > 0) {
    const primary = result.rootCauses[0];
    parts.push(`Based on my analysis, the primary root cause is **${primary.title}** (${(primary.confidence * 100).toFixed(0)}% confidence).`);
    parts.push('');
    parts.push(primary.description);
    parts.push('');
  }

  if (result.businessImpact.lostRevenue > 0) {
    parts.push(`**Estimated revenue at risk:** ${result.businessImpact.lostRevenueFormatted}`);
    parts.push('');
  }

  if (result.actions.length > 0) {
    parts.push('**Recommended next steps:**');
    for (const a of result.actions.slice(0, 3)) {
      parts.push(`- [${a.priority.toUpperCase()}] ${a.title}: ${a.description}`);
    }
    parts.push('');
  }

  if (result.geoOpportunity) {
    parts.push(`**Geographic insight:** ${result.geoOpportunity.narrative}`);
  }

  return parts.join('\n');
}
